version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - php
      - postgresql
    networks:
      - mynetwork

  php:
    image: php:8.0-fpm
    build:
      context: .
      dockerfile: php/Dockerfile.php
    volumes:
      - ./symfony:/var/www/
    depends_on:
      - postgresql
    networks:
      - mynetwork

    working_dir: /var/www/html
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork: